### ISSUE TITLE
Cabal Client

### ISSUE THREAD

**Issue by marzxxx90** [artem-alekseev/cabal_server#4]
May I ask what client need for this server?

**Comment by artem-alekseev** [comment]
This client https://drive.google.com/file/d/13whGyr_JKoc0nDwHVymx1QSzH7kOyMdr/view?usp=sharing

**Comment by marzxxx90** [comment]
thanks...may I ask what is the deferent of this server to your ep2 server?

**Comment by artem-alekseev** [comment]
This release ep8, ep8 is much newer than ep2

**Comment by wiltonsr** [comment]
What do I need to do with this client to correct connect on the docker server?

**Comment by artem-alekseev** [comment]
https://forum.ragezone.com/f459/cabal-server-in-docker-1202852/#post9118737
